### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by gitlyap** [xogeny/book-builder#8]
Hi,

there is  a make error when I compile the book:
```shell
python specs.py
Path: /opt/MBE/ModelicaBook
Traceback (most recent call last):
  File "specs.py", line 626, in <module>
    generate()
  File "./source/_sphinxext/xogeny/gen_utils.py", line 249, in generate
    _generate_plots()
  File "./source/_sphinxext/xogeny/gen_utils.py", line 154, in _generate_plots
    with open(os.path.join(path, "text", "plots", plot+".py"), "w+") as ofp:
IOError: [Errno 13] Permission denied: '/opt/MBE/ModelicaBook/text/plots/SIS.py'
Makefile:59: recipe for target 'specs' failed
make: *** [specs] Error 1
make: *** [Makefile:32: specs] Error 2
```

**Comment by xogeny** [comment]
I'm trying to find some time to revisit this.  But note that I don't really support the build process for the book.  You are welcome to build it yourself, but I can't really spend time helping you figure out how to get it working.
